version: 2

sources:
  - name: northwind
    schema: public   
    tables:
      - name: orders
      - name: order_items
      - name: customers
      - name: payment
      - name: shipments
      - name: products
      - name: suppliers
